outserver.api:
  domain: "http://localhost"
  port: 8091
  endpoint: "/api/endpoint1"

---

spring:
  profiles: production

outserver.api:
  domain: "https://api.run.pivotal.io"
  port:
  endpoint: "/v2/info"
