outserver.api:
  domain: "http://localhost"
  port: 8091
  endpoint: "/api/endpoint1"

---

spring:
  profiles: production

outserver.api:
  domain: "https://subdomain.corp.com"
  port: 8090
  endpoint: "/api/concept1"
